apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/thinhhja2001/code-sharing-be-deployment.git
      targetRevision: HEAD
      path: db

  destination:
    server: https://kubernetes.default.svc
    namespace: db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
