apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels: {}
  name: "code-sharing-be"

spec:
  selector:
    app: "code-sharing-be"
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
