apiVersion: v1
kind: Secret
metadata:
  name: redis-insight-basicauth
  namespace: redis
  labels:
    konghq.com/credential: basic-auth
type: Opaque
stringData:
  kongCredType: "basic-auth"
  username: "thinhhja2001"
  password: "Pa$$word"

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: redis-insight-basicauth-consumer
  namespace: redis
  annotations:
    kubernetes.io/ingress.class: kong
username: redis-insight-basicauth-consumer
credentials:
  - redis-insight-basicauth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: redis-insight-basicauth
  namespace: redis
  labels:
    konghq.com/credential: basic-auth
plugin: basic-auth
config:
  hide_credentials: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  namespace: redis
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: redis-insight-basicauth
    kubernetes.io/ingress.class: kong
spec:
  ingressClassName: kong
  rules:
    - host: redis-insight.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisinsight
                port:
                  number: 5540