apiVersion: v1
kind: Secret
metadata:
  name: redis-insight-basicauth
  namespace: redis
  labels:
    konghq.com/credential: basic-auth
type: Opaque
stringData:
  kongCredType: "basic-auth"
  username: "thinhhja2001"
  password: "Pa$$word"